
###
GET http://localhost:3000/api/binance/get24hs

###
GET http://localhost:3000/api/binance/getPrices


###
GET http://localhost:3000/api/binance/price/slpusdt

###
GET http://localhost:3000/api/binance/price/btcusdtd


###
GET http://localhost:3000/api/binance/24h/btcusdt

